package config

const (

  // Environment variable names
	GO_MA_ACTOR_KEYSET_VAR                   = "GO_MA_ACTOR_KEYSET"
	GO_MA_ACTOR_ENTITY_VAR                   = "GO_MA_ACTOR_ENTITY"
	GO_MA_ACTOR_DISCOVERY_TIMEOUT_VAR        = "GO_MA_ACTOR_DISCOVERY_TIMEOUT"
	GO_MA_ACTOR_DISCOVERY_RETRY_INTERVAL_VAR = "GO_MA_ACTOR_DISCOVERY_RETRY"
	GO_MA_ACTOR_DESIRED_PEERS_VAR            = "GO_MA_ACTOR_DESIRED_PEERS"
	GO_MA_ACTOR_LOW_WATERMARK_VAR            = "GO_MA_ACTOR_LOW_WATERMARK"
	GO_MA_ACTOR_HIGH_WATERMARK_VAR           = "GO_MA_ACTOR_HIGH_WATERMARK"
	GO_MA_ACTOR_CONNMGR_GRACE_VAR            = "GO_MA_ACTOR_CONNMGR_GRACE"
	GO_MA_ACTOR_LOGLEVEL_VAR                 = "GO_MA_ACTOR_LOGLEVEL"
	GO_MA_ACTOR_LOGFILE_VAR                  = "GO_MA_ACTOR_LOGFILE"
)
